### ISSUE TITLE
(scheme char) is missing

### ISSUE THREAD

**Issue by KeenS** [picrin-scheme/picrin#211]

**Comment by omasanori** [comment]
I'd love to work on this unless anyone has started to do yet.

My current design based on the comment of @wasabiz:
1. `char.c` handles ASCII only, so `(picrin base)` also does.
2. `r7rs` nitro contains an implementation of character-related procedures in `(scheme base)` and `(scheme char)` that is, at least, UTF-8 aware.
3. r7rs nitro adds `full-unicode` feature. (unless we decide not to use Unicode version 6.0 or later :dizzy_face:)
4. Tools to convert from Unicode Character Database to internal tables will be added to `etc/`.

What do you think?

**Comment by wasabiz** [comment]
Great! I can't wait for it :)
I love that idea to implement unicode features as an pluggable nitro.
Picrin's major policy is to achieve high compatibility with various kinds
of environment even without libc, and I think UTF-8/Unicode is too big to
be part of the core (only supporting utf-8 should be small enough, though).
BTW, I guess you probably must be annoyed using both your repository and
picrin's. I have missed chances so far but I give you permission to get
access to picrin repo. Is it ok for you? Even after you got the right
development flow would not change. Every big modification against the core
should be requested via pull request (@keens has followed that rules, too).
For small bugfixes you can push directly to master anytime!

2015年6月26日(金) 14:41 OGINO Masanori <notifications@github.com>:

**Comment by omasanori** [comment]
Of course. I'm glad to become a collaborator.

BTW, when my modification is related both benz and picrin, what should I do?
Sending a PR to benz and another to picrin? Sending a PR including diffs on `extlib/benz/` to picrin?

**Comment by KeenS** [comment]
@omasanori Since benz is a subtree of picrin, PRing only to picrin will do enough. The one who merged will push the patch to benz. As such, be careful not to mix commit to benz and commit to picrin. Keep commit log clean.

**Comment by omasanori** [comment]
@KeenS I see.

**Comment by wasabiz** [comment]
@omasanori 

I sent you an invitation. Please check it out.

**Comment by omasanori** [comment]
@wasabiz Confirmed. Thanks!
