### ISSUE TITLE
Why not control benz under git-subtree?

### ISSUE THREAD

**Issue by KeenS** [picrin-scheme/picrin#236]
You know git-submodule is annoying. CI tests against some of my PR are failing because git-submodule don't contain submodule codes itself but only has entry point.

Git-subtree includes subtree's sources and diffs, and thus you can control whole source of parent project in one git repository.

How do you think @wasabiz @zeptometer @stibear @koba-e964

**Comment by wasabiz** [comment]
closing as fixed
