### ISSUE TITLE
explicit renaming is broken

### ISSUE THREAD

**Issue by zeptometer** [picrin-scheme/picrin#241]
``` scheme
(import (scheme base)
        (scheme write))
 
(define-syntax hoo
  (er-macro-transformer
   (lambda (form r cmp)
	 (if (cmp (r 'hoge) (cadr form))
		 `(,(r 'write) "You got")
		 `(,(r 'write) ',(cadr form))))))
  
(hoo hoge) ; should display "You got", but got "hoge"
```

This bug is caused by the way picrin identifier system treats unbound symbol. In this case, `(r 'hoge)` returns fresh uninterned symbol. According to definition of er comparator and identifier=?, `(cmp (r 'hoge) (cadr form))` compares this fresh uninterned symbol with `'hoge` by `eq?`. Of cource, this returns false.

Now we know why this bug occurs, but It seems difficult to fix this bug. One idea is to make top-level binding for each macro expansion, so that make-identifier returns same value for same symbol. How do you think?

**Comment by wasabiz** [comment]
@zeptometer 

Can you tell me which version (commit id) of picrin you use?

**Comment by wasabiz** [comment]
FYI, existing almost all bugs related to hygienic macros will be removed in the near future when we replace our macro expander with a new one. The next system will be more robust and easier to use. This bug should also be solved then.

**Comment by zeptometer** [comment]
@wasabiz Tested version is `c399bd3`.
> FYI, existing almost all bugs related to hygienic macros will be removed in the near future when we replace our macro expander with a new one. The next system will be more robust and easier to use. This bug should also be solved then.

That's a good news. I'm looking forward to seeing the new expander:)

**Comment by KeenS** [comment]
@zeptometer 
FYI, this code prints "You got", though I don't know why.

```schem
(define-syntax hoo
  (er-macro-transformer
   (lambda (form r cmp)
     (if (cmp (r 'hoge) (r (cadr form)))
         `(,(r 'write) "You got")
         `(,(r 'write) ',(cadr form))))))
```

**Comment by wasabiz** [comment]
fixed
