### ISSUE TITLE
Segmentation fault since the removal of in-library

### ISSUE THREAD

**Issue by omasanori** [picrin-scheme/picrin#266]
According to the [build history](https://travis-ci.org/picrin-scheme/picrin/builds), the commit https://github.com/picrin-scheme/picrin/commit/8604e18719ad6205da5fafe40c7e2741df94446f broke something at `gcc -m32`.

**Comment by wasabiz** [comment]
@omasanori 

Thanks for the report. I did some investigation for a while but got nothing about the cause. I'll leave the commit reverted until I find the segv bug, which I think is maybe in gc.c or around pic_obj_alloc calls.

**Comment by wasabiz** [comment]
Fixed. Probably travis's fault.
