### ISSUE TITLE
-0.1 is evaluated as 0.9

### ISSUE THREAD

**Issue by omasanori** [picrin-scheme/picrin#282]
Confirmed at  214c18adcff24d45677957842ccd59dcebd814fc.
```scheme
-0.1 ;=> 0.9000
-0.2 ;=> 0.8000
; ...
-0.9 ;=> 0.1000
-1.0 ;=> -1.0000
-1.1 ;=> -1.9000
-1.2 ;=> -1.8000
; ...
-1.9 ;=> -1.1000
-2.0 ;=> -2.0000
-2.1 ;=> -2.9000
; ...
```

**Comment by wasabiz** [comment]
Looks too bad...

**Comment by KeenS** [comment]
It seems not the reader or the evaluator but the writer has problem.

```
(write (+ 0.1 -0.1)) ; -> 0.0
```

**Comment by KeenS** [comment]
@wasabiz @omasanori 
I found the cause but don't have time to fix, so please fix it.
At file.c, there are two problems.

1. https://github.com/picrin-scheme/picrin/blob/master/extlib/benz/file.c#L354 casting `-0.1` to int results `0`; erases sign information
2. https://github.com/picrin-scheme/picrin/blob/master/extlib/benz/file.c#L357 `floor(-0.1)` results `-1.0`. Or more to say, `floor`ing negative float is not a good idea. Use `modf`.
