### ISSUE TITLE
(picrin tls)

### ISSUE THREAD

**Issue by omasanori** [picrin-scheme/picrin#291]
For better or worse, we use TLS for daily communications nowadays, so will we.
(I will tackle this after launching Unicode support, but of course you can do it if you can't wait until I finally start to do. :smile:)
Here are some references:
- [OpenSSL docs](https://www.openssl.org/docs/)
- [OpenSSL wiki](https://wiki.openssl.org/index.php/Main_Page)
- [libtls man page](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man3/tls_accept_fds.3)
  - The APIs from OpenBSD folks are dramatically simplified from powerful-but-complicated OpenSSL's. We should learn from this.
- [s2n usage guide](https://github.com/awslabs/s2n/blob/master/docs/USAGE-GUIDE.md)
  - This new SSL/TLS library from AWS Labs is also well worth learning.
- [SSL libraries comparison table in the cURL site](http://curl.haxx.se/docs/ssl-compared.html)
- [Gauche's TLS library](https://github.com/shirok/Gauche/blob/master/ext/tls/tls.scm)
- [The Guile binding for GnuTLS](http://gnutls.org/manual/gnutls-guile/index.html)
- [openssl egg for Chicken Scheme](http://wiki.call-cc.org/eggref/4/openssl)

**Comment by KeenS** [comment]
I'd like to have simpler one. I don't think picrin should be able to generate certificates.

**Comment by omasanori** [comment]
@KeenS I'm on your side. Kitchen-sink approaches should be avoided, IMHO, especially on security.

Also, I think general cryptography-related things should be provided by, say `(picrin crypto)`, `(picrin rsa)` or so on, if we want them.
Proposal: the role of `(picrin tls)` is providing network connection on TLS (and/or DTLS.)
