### ISSUE TITLE
srfi 1 test failing on OS X

### ISSUE THREAD

**Issue by saysjonathan** [picrin-scheme/picrin#329]
```
$ make test-srfi
<snip>
case 13 FAIL: (iota 5 0 -0.1)
   expected (0 -0.1 -0.2 -0.3 -0.4) but got (0 -0.1 -0.2 -0.30000000000000007 -0.4)
<snip>
 FAIL: (iota 5 0 -0.1)
   expected (0 -0.1 -0.2 -0.3 -0.4) but got (0 -0.1 -0.2 -0.30000000000000007 -0.4)
```

**Comment by KeenS** [comment]
Verified. It is basically precision problem but there might be something we can do for

**Comment by saysjonathan** [comment]
Precision issues appear to transcend OS. Verified on Linux:

```
> (+ 0.1 (+ 0.1 (+ 0.1)))
0.30000000000000007
```

**Comment by wasabiz** [comment]
It seems we cannot fix this issue. The test case should be changed.

**Comment by saysjonathan** [comment]
What's preventing this from being fixed?

**Comment by wasabiz** [comment]
Picrin doesn't have internal representation of exact rational number so `0.1` is implicitly converted to double. We cannot avoid this kind of error as long as FPU computes in binary. Meanwhile, I got a similar result running python:

```
$ python
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 0.1 + 0.1 + 0.1
0.30000000000000004
>>> 
```

**Comment by saysjonathan** [comment]
Makes perfect sense.

Same for Ruby:
```
irb(main):001:0> 0.1 + 0.1 + 0.1
=> 0.30000000000000004
```

and Haskell:
```
Prelude> 0.1 + 0.1 + 0.1
0.30000000000000004
```

:+1: for changing the test case.

**Comment by saysjonathan** [comment]
In case anyone is interested, Chibi and Guile both work:

```
$ chibi-scheme
> (* 0.1 3)
0.3
> (* 0.1 12)
1.2

$ guile
guile> (* 0.1 3)
0.3
guile> (* 0.1 12)
1.2
```
