### ISSUE TITLE
`equal?` does not recognize dictionaries

### ISSUE THREAD

**Issue by nyuichi** [picrin-scheme/picrin#333]

**Comment by johnwcowan** [comment]
IMO this should be closed as "wontfix".  Scheme `equal?` does what it does, and it is unportable (though still conformant) to extend it.  We already have a portable and flexible comparison mechanism, namely SRFI 128 comparators, which can be improved quite a bit with a slightly non-portable implementation.

**Comment by nyuichi** [comment]
@johnwcowan 

Still, the scheme report allows extension of the semantics for implementation-specific data types, right? Actually, the kernel of picrin is *NOT* implementing the scheme language. It can be even built without library system nor define-syntax. That's why I think extending built-in procedures would be an effective way to provide functionality keeping the core component small.
OTOH I agreed to your point that it is not pleasant to let scheme users depend on our own semantic extension. From the schemers' (or scheme committees') viewpoint, SRFI128 might be the best option. As of now we are focusing on making the kernel component more usable. We will work on srfis after the work is done.

**Comment by nyuichi** [comment]
fixed
