### ISSUE TITLE
R7RS promise bugs (on corner cases)

### ISSUE THREAD

**Issue by yhara** [picrin-scheme/picrin#339]
Hi,

While writing [this article](https://nacl-ltd.github.io/2016/05/31/delay-force.html), I found that picrin behaves differently from Chibi Scheme and Gauche.

```scm
(import (scheme base) (scheme lazy) (scheme write))

;; Test 1 : forcing op should make np resolved

(define x 0)
(define np (delay (begin
                    (set! x (+ x 1))
                    (if (= x 1) 'ok 'ng))))

(define op (delay-force np))

(force op)
(display (force np))(newline)  ; expected ok but got ng

;; Test 2: reentrancy test

(define flag #f)
(define p (delay (if flag
                   'ok
                   (begin
                     (set! flag #t)
                     (force p)
                     'ng))))
(display (force p))  ; expected ok but got ng
```

I'll write a patch if you want me to.

**Comment by KeenS** [comment]
Hmm that's interesting. As you described in your blog, what matters seems reentrancy.

Could I ask you to send us patch? [Here](https://github.com/picrin-scheme/picrin/blob/master/contrib/20.r7rs/scheme/lazy.scm#L23) the code and the patch won't be so big. Thank you.

**Comment by stibear** [comment]
I tried to fix these bugs and have fixed the second bug easily.

However, to fix the first problem requires to overwrite pointers (ref. http://srfi.schemers.org/srfi-45/srfi-45.html : this uses a list as a 'box' instead of the pointer).

In our implementation, a promise is a record. I'm worried that wrapping by a list takes some merits of record types from our promise.

What do you think of this?

**Comment by KeenS** [comment]
Oh, sorry @yhara I asked you to send patch but @stibear has done the task.

**Comment by yhara** [comment]
@KeenS no problem :-)

> In our implementation, a promise is a record. I'm worried that wrapping by a list takes some merits of record types from our promise.

One merit of implementing promise as record is that you can hide implementation details from user. From that point of view, wrapping box with record is better than wrapping record with box.

**Comment by nyuichi** [comment]
@yhara @keens @stibear

Hi, guys

Could someone tell me why the second test is expected to be ok? I still don't figure out it. Just pointing the paragraph in the spec is enough.

Thanks.

**Comment by KeenS** [comment]
@nyuichi it's sensitive, but I found this sentence.

> The value of the promise must be cached (or “memoized”) so that if it is forced a second time, the previously computed value is returned.

At the first *call* of `force`, the expression is expected to return `ng` but in the expression, the second *call* of `force` return `ok` (that's the first *return* from `force`). Apparently, the first *computed value* is the first returned value.

**Comment by nyuichi** [comment]
@KeenS 

Oh, tha sounds crazy... But that's a good explanation. I understood it.
