### ISSUE TITLE
Missing source files?

### ISSUE THREAD

**Issue by dcurrie** [picrin-scheme/picrin#351]
In a commit on May 12, 2017, "bugfix: dyn_env is not properly restored on delim-cont call", a change was made to error.c in the generated file lib/ext but not to the corresponding source file in piclib.

On a related note, it's necessary for me to change the piclib/*.scm source files to use `write-string` instead of `display`; otherwise some of the output goes to the console instead of the pipe into the output file (on macOS).  Also, the files in piclib use quotes instead of \<\> around #include file names.

The build is failing on Github.

When I fix the build locally by making the changes above, as well as 
- replacing `pic_raise(pic, e)` with `pic_funcall(pic, "raise", 1, e)` in contrib/20.r7rs/src/load.c
- removing `static` from `pic_fmemopen` in lib/ext/port.c
- adding a declaration for `pic_fmemopen` in lib/include/picrin/extra.h
- replacing `pic_raise(pic, e)` with `pic_funcall(pic, "raise", 1, e)` twice in tools/mkloader.pl

the resulting picrin application hangs on launch.

All this makes me wonder if there are missing file updates on Github.

**Comment by omasanori** [comment]
Thank you for reporting, @dcurrie!

I also found the build issues some day and your pic_raise fix looks good to me. However, I am unsure whether the pic_fmemopen fix is correct or not since the API had been public and changed to private IIRC.

@wasabiz, your thoughts?
