### ISSUE TITLE
build fails on mac os 

### ISSUE THREAD

**Issue by hak-ano** [picrin-scheme/picrin#353]
$ make

cc -I./lib/include -I./include -Wall -Wextra -O2 -g -DNDEBUG=1   -c -o src/load_piclib.o src/load_piclib.c
src/load_piclib.c:15:20: warning: implicit declaration of function 'pic_fmemopen' is
      invalid in C99 [-Wimplicit-function-declaration]
  pic_value port = pic_fmemopen(pic, str, strlen(str), "r"), e;
                   ^
src/load_piclib.c:15:13: error: initializing 'pic_value' (aka 'struct value') with an
      expression of incompatible type 'int'
  pic_value port = pic_fmemopen(pic, str, strlen(str), "r"), e;
            ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by KeenS** [comment]
It's a known problem. As you can see in the build status badge in README, master itself is broken, not a specific problem to macOS.

**Comment by pranomostro** [comment]
Does this mean this project is not maintained any more?

**Comment by KeenS** [comment]
I guess, yes. 
@nyuichi Do you have any comments?
