### ISSUE TITLE
Is Picrin dead?

### ISSUE THREAD

**Issue by FinnG** [picrin-scheme/picrin#354]
I've been looking at integrating Picrin Scheme into a project of mine, but there are a myriad of build/configuration issues. Is this project still maintained? I see there have been no commits for a year and the build has been broken for a similar amount of time.

Does anyone know what the status is?

**Comment by KeenS** [comment]
I think @nyuichi is busy or have lost interest to picrin. There are very low probability for him to restart developing.

**Comment by FinnG** [comment]
Ah, that's a shame :-). Thanks for the quick reply.
