### ISSUE TITLE
Botbot Acquired, link no longer works

### ISSUE THREAD

**Issue by jasonhemann** [picrin-scheme/picrin#355]
[The botbot link](https://github.com/picrin-scheme/picrin/blob/2af16bc88fbfca2efafd27ca9e5006d73c06f6fb/docs/intro.rst?plain=1#L32) you mention in the source no longer directs where you would expect, presumably since the acquisition.

**Comment by omasanori** [comment]
OK, I will look into it and update the docs. Thank you for reporting!
