### ISSUE TITLE
Core dump from REPL

### ISSUE THREAD

**Issue by sanel** [picrin-scheme/picrin#51]
Hi,

I just pulled picrin source from the repo, and after issuing these in REPL:
```scheme
> (define (range s e) 
     (if (>= s e) 
       (list)
       (cons s (range (+ 1 s) e))))
> (apply + (range 1 10000))
```
I'm getting core dump. Any idea what can be wrong?

Best, Sanel

**Comment by wasabiz** [comment]
already fixed
